In [5]:
lst = ["chris", "john", "eric", "lynn", "jane", "jason"]
print(lst[1:4])
print(len(lst))
print(lst[-1])
print(type(lst[1]))
lst.append("jinny")
lst.insert(1, "amy")
lst.remove("john")
print(lst)

# 刪除list中的11
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 11, 11]
while 11 in num:
    num.remove(11)
print(num)




['john', 'eric', 'lynn']
6
jason
<class 'str'>
['chris', 'amy', 'eric', 'lynn', 'jane', 'jason', 'jinny']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15]


In [12]:
import numpy as np
lst = [[1,2,3],[4, 5,6],[7,8,9]]
ary = np.array(lst)
print(ary)
print(lst)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
while True:
    month = input("請輸入月份，或輸入 'exit' 退出: ").strip()

    if month.lower() == 'exit':
        print("程式結束")
        break

    if month.lower() == "february" or int(month) == 2:
        print(f"{month.capitalize()} 有 28/29 天")
    elif month.lower() in ["january", "march", "may", "july", "august", "october", "december"] or int(month) in [1, 3, 5, 7, 8, 10, 12]:
        print(f"{month.capitalize()} 有 31 天")
    elif month.lower() in ["april", "june", "september", "november"] or int(month) in [4, 6, 9, 11]:
        print(f"{month.capitalize()} 有 30 天")
    else:
        print("無效的月份")


無效的月份
12 有 31 天
程式結束


In [28]:
import random

# random.seed(9001)
# 生成包含100個隨機整數的列表（範圍從1到100）
numbers = [random.randint(1, 100) for _ in range(10)]

# 初始化結果列表和計數器
odd_numbers = []
even_numbers = []
odd_count = 0
even_count = 0

# 使用 for-in 循環判斷每個數是奇數還是偶數
for num in numbers:
    if num % 2 == 0:
        even_numbers.append(num)
        even_count += 1
    else:
        odd_numbers.append(num)
        odd_count += 1

# 打印結果
print(f"奇數列表: {odd_numbers}")
print(f"偶數列表: {even_numbers}")
print(f"奇數數量: {odd_count}")
print(f"偶數數量: {even_count}")

奇數列表: [5, 39, 33, 9, 73, 33, 73, 7]
偶數列表: [78, 66]
奇數數量: 8
偶數數量: 2


In [32]:
import random
lst1 = [random.randint(1,30) for i in range(3)]
lst2 = [random.randint(1,30) for i in range(3)]
lst1 = [3, 5, 15]
lst2 = [2, 1, 6]
val = 0

for idx in range(len(lst1)):
    val += ( lst1[idx] - lst2[idx] ) ** 2
print(val)
print(lst1)
print(lst2)

98
[3, 5, 15]
[2, 1, 6]


In [1]:
import random
# random.seed(2913)
shiptos = ["台北", "桃園", "新竹", "台中", "高雄"]
prods = ["electronics", "food", "clothing", "household", "others"]
lis_all = []
for prod in prods:
    lis_all.append([prod] + [random.randint(1,99) for i in range(random.randint(5,20))] + [random.randint(0,4)])

# print(lis_all)
# print(len(lis_all))
for i in range(len(lis_all)):
    if lis_all[i][0] in ["electronics", "clothing", "household" ]:
        count = 0
        for n in range(1, len(lis_all[i]) - 1):
            count += lis_all[i][n]
        print(f"Total Ship with {lis_all[i][0]}, Ship Qty are {count} unit, Ship To {shiptos[lis_all[i][len(lis_all[i]) - 1]]}")
print("-------------------------------------------------------------")
for i in range(len(lis_all)):
    if lis_all[i][0] in ["food", "others" ]:
        itm = 0
        print(f"**Product:{lis_all[i][0]} (Ship To: {shiptos[lis_all[i][len(lis_all[i]) - 1]]}), \neach item as list:")
        for n in range(1, len(lis_all[i]) - 1):
            itm += 1
            print(f"Item:{itm}, Qty:{lis_all[i][n]}")


Total Ship with electronics, Ship Qty are 332 unit, Ship To 台中
Total Ship with clothing, Ship Qty are 746 unit, Ship To 新竹
Total Ship with household, Ship Qty are 468 unit, Ship To 台北
-------------------------------------------------------------
**Product:food (Ship To: 台北), 
each item as list:
Item:1, Qty:85
Item:2, Qty:46
Item:3, Qty:95
Item:4, Qty:87
Item:5, Qty:23
Item:6, Qty:49
Item:7, Qty:52
Item:8, Qty:63
Item:9, Qty:72
Item:10, Qty:24
Item:11, Qty:2
Item:12, Qty:61
Item:13, Qty:78
**Product:others (Ship To: 高雄), 
each item as list:
Item:1, Qty:20
Item:2, Qty:39
Item:3, Qty:2
Item:4, Qty:88
Item:5, Qty:9
Item:6, Qty:86
Item:7, Qty:57
Item:8, Qty:56
Item:9, Qty:78
Item:10, Qty:63
Item:11, Qty:88
Item:12, Qty:7
Item:13, Qty:99
Item:14, Qty:47
Item:15, Qty:81
Item:16, Qty:73
Item:17, Qty:75


In [6]:
import random
# random.seed(2913)
shiptos = ["台北", "桃園", "新竹", "台中", "高雄"]
prods = ["electronics", "food", "clothing", "household", "others"]

lis_all = [[prod] + [random.randint(1, 100) for _ in range(random.randint(5, 20))] + [random.randint(0, 4)] for prod in prods]
# print(lis_all)

for item in lis_all:
    prod, *quantities, shipto_index = item
    shipto = shiptos[shipto_index]
    
    if prod in ["electronics", "clothing", "household"]:
        total_qty = sum(quantities)
        print(f"Total Ship with {prod}, Ship Qty are {total_qty} unit, Ship To {shipto}")
        
for item in lis_all:        
    if prod in ["food", "others"]:
        print(f"**Product:{prod} (Ship To: {shipto}), \neach item as list:")
        for idx, qty in enumerate(quantities, start=1):
            print(f"Item:{idx}, Qty:{qty}")

Total Ship with electronics, Ship Qty are 978 unit, Ship To 台中
Total Ship with clothing, Ship Qty are 283 unit, Ship To 台北
Total Ship with household, Ship Qty are 791 unit, Ship To 台北
**Product:others (Ship To: 桃園), 
each item as list:
Item:1, Qty:14
Item:2, Qty:26
Item:3, Qty:68
Item:4, Qty:83
Item:5, Qty:7
Item:6, Qty:4
Item:7, Qty:40
Item:8, Qty:99
Item:9, Qty:15
Item:10, Qty:49
Item:11, Qty:86
Item:12, Qty:75
Item:13, Qty:15
**Product:others (Ship To: 桃園), 
each item as list:
Item:1, Qty:14
Item:2, Qty:26
Item:3, Qty:68
Item:4, Qty:83
Item:5, Qty:7
Item:6, Qty:4
Item:7, Qty:40
Item:8, Qty:99
Item:9, Qty:15
Item:10, Qty:49
Item:11, Qty:86
Item:12, Qty:75
Item:13, Qty:15
**Product:others (Ship To: 桃園), 
each item as list:
Item:1, Qty:14
Item:2, Qty:26
Item:3, Qty:68
Item:4, Qty:83
Item:5, Qty:7
Item:6, Qty:4
Item:7, Qty:40
Item:8, Qty:99
Item:9, Qty:15
Item:10, Qty:49
Item:11, Qty:86
Item:12, Qty:75
Item:13, Qty:15
**Product:others (Ship To: 桃園), 
each item as list:
Item:1, Qty:14
It

In [18]:
list(range(10))
a = list(range(2, 30, 3))
print(a)

[2, 5, 8, 11, 14, 17, 20, 23, 26, 29]


In [1]:
def get_days_in_month(month):
    days_in_month = {
        'january': 31, 'february': 28, 'march': 31, 'april': 30,
        'may': 31, 'june': 30, 'july': 31, 'august': 31,
        'september': 30, 'october': 31, 'november': 30, 'december': 31
    }
    
    month = month.lower()
    if month in days_in_month:
        return days_in_month[month]
    else:
        return "無效的月份"

# 主程式
while True:
    month = input("請輸入月份（英文全名），或輸入 'exit' 退出: ").strip()
    
    if month.lower() == 'exit':
        print("程式結束")
        break
    
    days = get_days_in_month(month)
    if isinstance(days, int):
        print(f"{month.capitalize()} 有 {days} 天")
    else:
        print(days)

April 有 30 天
程式結束
